name: Build the cloud app, test and deploy
on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  # cloud-endpoints-tests-prod:
  #   if: github.event.pull_request.merged == true
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v4

  #     - name: Build prod test image
  #       run: |
  #         docker build -t darkbrains/cloud:local -f ./bin/Dockerfile ./bin

  #     - name: Run Tests Prod
  #       run: |
  #         bash ./tests/tests.sh

  #     - name: Report Status For Tests Prod
  #       if: always()
  #       uses: ravsamhq/notify-slack-action@v2
  #       with:
  #         status: ${{ job.status }}
  #         notify_when: "success,failure"
  #         footer: "<{run_url}|View Run>"
  #         notification_title: "cloud-endpoints-tests-prod"
  #         message_format: "{emoji} *{job}* {status_message} on <{commit_url}|{commit_sha}>"
  #         token: ${{ secrets.repo_token }}
  #       env:
  #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

  cloud-ci:
    if: github.event.pull_request.merged == true
    # needs: cloud-endpoints-tests-prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        run: |
          docker image build -t darkbrains/cloud:${{ github.sha }} -f ./bin/Dockerfile ./bin
          docker image push darkbrains/cloud:${{ github.sha }}

      # - name: Push README to Docker Hub
      #   uses: christian-korneck/update-container-description-action@v1
      #   env:
      #     DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
      #   with:
      #     destination_container_repo: blackdocs/jermuk-city
      #     provider: dockerhub
      #     readme_file: './bin/README.md'

      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: Dark-brains/live-environments
          ref: main
          token: ${{ secrets.TOKEN_GITHUB }}

      # - name: Import GPG key
      #   uses: crazy-max/ghaction-import-gpg@v6
      #   with:
      #     gpg_private_key: ${{ secrets.GPG_KEY }}
      #     git_user_signingkey: true
      #     git_commit_gpgsign: true

      - name: Delever to K8S
        run: |
          sed -i "s|docker.io/darkbrains/cloud:[^ ]*|docker.io/darkbrains/cloud:${{ github.sha }}|" ./saas/cloud/values.yaml
        working-directory: ./

      - name: Sign commit and push changes
        run: |
          git add .
          git config --local user.email "blackdocscloud@gmail.com"
          git config --local user.name "darkbrains-bot"
          git commit -m "Update image tag for cloud"
          git push

      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notify_when: "success,failure"
          footer: "<{run_url}|View Run>"
          notification_title: "cloud CI"
          message_format: "{emoji} *{workflow}* {status_message} on <{commit_url}|{commit_sha}>"
          token: ${{ secrets.repo_token }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
