# name: Cloud Endpoints Tests
# on:
#   push:
#     branches-ignore:
#       - main

# jobs:
#   node-js-endpoints-tests:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4

#       - name: Build test image
#         run: |
#           docker build -t darkbrains/cloud:local -f ./bin/Dockerfile ./bin

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           registry: docker.io
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Run Tests
#         run: |
#           bash ./tests/tests.sh

#       - name: Report Status For Tests
#         if: always()
#         uses: ravsamhq/notify-slack-action@v2
#         with:
#           status: ${{ job.status }}
#           notify_when: "success,failure"
#           footer: "<{run_url}|View Run>"
#           notification_title: "cloud-endpoints-tests"
#           message_format: "{emoji} *{workflow}* {status_message} on <{commit_url}|{commit_sha}>"
#           token: ${{ secrets.repo_token }}
#         env:
#           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
